name: Bot
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

# generate and push changelogs to master only
jobs:
  create-release:
    name: Create GitHub Release
    if: github.repository == 'ashutoshgngwr/noice'
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow --tags -f
      - id: tag_info
        run: |
          export TAG_NAME="${GITHUB_REF/'refs/tags/'/''}"
          export TAG_BODY="$(git tag  --list --format='%(contents:body)' $TAG_NAME)"
          export TAG_BODY="${TAG_BODY//'%'/'%25'}"
          export TAG_BODY="${TAG_BODY//$'\n'/'%0A'}"
          export TAG_BODY="${TAG_BODY//$'\r'/'%0D'}"
          echo "::set-output name=name::${TAG_NAME}"
          echo "::set-output name=body::${TAG_BODY}"
      - uses: softprops/action-gh-release@v1
        with:
          name: v${{ steps.tag_info.outputs.name }}
          body: ${{ steps.tag_info.outputs.body }}

  generate-docs:
    name: Generate Docs
    if: github.repository == 'ashutoshgngwr/noice'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      - name: Generate changelog
        run: |
          export CHANGELOG_FILE="docs/CHANGELOG.md"
          export RELEASE_URL="https://github.com/ashutoshgngwr/noice/releases/tag/%(tag)"
          export GIT_TAG_FMT="## [v%(tag)]($RELEASE_URL)%0a%0a**%(creatordate:format:%A, %-d %B %Y)**%0a%0a%(contents:body)"

          echo "# Changelog" > $CHANGELOG_FILE
          echo "" >> $CHANGELOG_FILE
          echo "All notable changes to this project will be documented in this file." >> $CHANGELOG_FILE
          echo "" >> $CHANGELOG_FILE
          git tag --sort="-creatordate" --format="$GIT_TAG_FMT" --list >> $CHANGELOG_FILE

          sed -i -E "s@(#)([0-9]+)@[\1\2](https://github.com/$GITHUB_REPOSITORY/issues/\2)@g" docs/CHANGELOG.md
      - name: Generate list of code authors
        run: |
          export LIST_PATH="docs/_data/authors/code.yaml"
          git log --pretty="- %an <%ae>%n- %cn <%ce>" > "$LIST_PATH"
          git log --pretty="%b" | grep "Co-authored-by:" >> "$LIST_PATH"
          sed -i -e 's/Co-authored-by:/-/g' -e 's/\r$//' "$LIST_PATH"
          sort -u -o "$LIST_PATH" "$LIST_PATH"
          sed -i -e '/noreply@github.com/d' -e '/hosted@weblate.org/d' -e '/\[bot\]/d' "$LIST_PATH"
          sed -i -E 's/(.*) <(.*)>/\1 | [\2](mailto:\2)/g' "$LIST_PATH"
      - name: Commit changes
        run: |
          git config --local user.email "noreply@github.com"
          git config --local user.name "GitHub"
          if [ -n "$(git diff docs/)" ]; then
            git add docs/
            git commit -m "chore(project): update docs" \
              --author "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          fi
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
